server:
  port: 8000
spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://mysql:3306/payment
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver  
###服务注册到eureka集群地址
eureka:
  client:
    service-url:
           defaultZone: http://eureka-server:8100/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
